- name: Copy webapp/rust from local to remote
  ansible.posix.synchronize:
    src: ../webapp/rust/
    dest: /home/isucon/webapp/rust/
    recursive: true
    rsync_opts:
      - "--exclude=target"
  notify:
    - restart_webapp

- name: Deploy init files
  ansible.builtin.copy:
    src: "../{{ item }}"
    dest: "/home/isucon/{{ item }}"
    owner: isucon
    group: isucon
    mode: "0644"
  with_items:
    - webapp/sql/init.sql
